server:
  port: 8080

spring:
  application:
    name: swim-admin
  datasource:
    url: jdbc:mysql://localhost:3306/xiangyongshe?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true
    username: root
    password: ab123168
    driver-class-name: com.mysql.cj.jdbc.Driver
  sql:
    init:
      mode: always
      schema-locations: classpath:db/schema.sql
      data-locations: classpath:db/data.sql
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: Asia/Shanghai

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
  global-config:
    db-config:
      id-type: auto
      logic-delete-field: deleted
      logic-delete-value: 1
      logic-not-delete-value: 0

app:
  jwt:
    secret: "xiangshe-secret-key-change-me-please-32bytes"
    expiration-seconds: 7200
  upload-dir: "/Users/itzhan/Desktop/毕业设计/李森2/swim-admin/uploads"
  upload-url-prefix: "/uploads/"

logging:
  level:
    root: info
